language: go

go:
  - tip
  - "1.10.x"

before_install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls

script:
  - go test ./... -coverprofile=coverage.txt -covermode=atomic
  - $GOPATH/bin/goveralls -coverprofile=coverage.txt -service=travis-ci

after_success:
  - bash <(curl -s https://codecov.io/bash)